services:
  - type: web
    name: Raider-Bot
    env: python
    plan: free
    region: oregon
    runtime: python3.10
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
